[package]
name = "hirola-kit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptosfmt-pretty-printer = "0.1.6"
rstml = "0.10.6"
syn = { version = "2.0.18", features = [ "visit", "full", "extra-traits" ] }
leptosfmt-prettyplease = { features = [ "verbatim" ], version = "0.2.11" }
proc-macro2 = { version = "1.0.52", features = [ "span-locations" ] }
thiserror = "1.0.40"
crop = "0.3.0"
serde = { version = "1.0.163", features = [ "derive" ] }

[dev-dependencies]
indoc = "2.0.1"
insta = "1.28.0"
quote = "1.0.26"